set(LIBOPENCM3_DIR ${CMAKE_SOURCE_DIR}/thirdparty/libopencm3)

add_custom_target(libopencm3
    COMMAND make PREFIX=${TOOLCHAIN_BIN_DIR}/${TOOL_CHAIN_PREFIX}- TARGETS=stm32/f1 all
    WORKING_DIRECTORY ${LIBOPENCM3_DIR}
)

# Expected for target to include EXTERNAL_INCLUDE_DIRECTORIES
include_directories(${LIBOPENCM3_DIR}/include)

# Expected for target to include EXTERNAL_LINK_DIRECTORIES
link_directories(${LIBOPENCM3_DIR}/lib)


set(LIBOPENCM3_LIB opencm3_stm32f1)

set(LIBOPENCM3_LINKER_FLAGS --static -nostartfiles)

# Target should include each of these EXTERNAL_*
#set(EXTERNAL_INCLUDE_DIRECTORIES ${EXTERNAL_INCLUDE_DIRECTORIES} ${LIBOPENCM3_DIR/}include)
#set(EXTERNAL_LINK_DIRECTORIES ${EXTERNAL_LINK_DIRECTORIES} ${LIBOPENCM3_DIR}/lib})
set(EXTERNAL_LINKER_FLAGS ${EXTERNAL_DEPENDENCIES_LINKER_FLAGS} ${LIBOPENCM3_LINKER_FLAGS})
set(EXTERNAL_LIBS ${EXTERNAL_LIBS} ${LIBOPENCM3_LIB})
set(EXTERNAL_DEPENDENCIES ${EXTERNAL_DEPENDENCIES} libopencm3)
